version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    restart: unless-stopped
    env_file:
      - .env.production
    # Opcional: para desarrollo con hot reload
    # volumes:
    #   - ./src:/app/src
    #   - ./public:/app/public
