version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    restart: unless-stopped
    env_file:
      - .env
    # Opcional: para desarrollo con hot reload
    # volumes:
    #   - ./src:/app/src
    #   - ./public:/app/public
