/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/document/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["documents_document_list"];
        put?: never;
        post: operations["documents_document_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/document/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Documento. */
                id: number;
            };
            cookie?: never;
        };
        get: operations["documents_document_read"];
        put: operations["documents_document_update"];
        post?: never;
        delete: operations["documents_document_delete"];
        options?: never;
        head?: never;
        patch: operations["documents_document_partial_update"];
        trace?: never;
    };
    "/documents/typedocument/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["documents_typedocument_list"];
        put?: never;
        post: operations["documents_typedocument_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/typedocument/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Tipo de Documento. */
                id: number;
            };
            cookie?: never;
        };
        get: operations["documents_typedocument_read"];
        put: operations["documents_typedocument_update"];
        post?: never;
        delete: operations["documents_typedocument_delete"];
        options?: never;
        head?: never;
        patch: operations["documents_typedocument_partial_update"];
        trace?: never;
    };
    "/tds/assets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tds_assets_list"];
        put?: never;
        post: operations["tds_assets_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tds/assets/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Bien. */
                id: number;
            };
            cookie?: never;
        };
        get: operations["tds_assets_read"];
        put: operations["tds_assets_update"];
        post?: never;
        delete: operations["tds_assets_delete"];
        options?: never;
        head?: never;
        patch: operations["tds_assets_partial_update"];
        trace?: never;
    };
    "/tds/status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tds_status_list"];
        put?: never;
        post: operations["tds_status_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tds/status/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Estado. */
                id: number;
            };
            cookie?: never;
        };
        get: operations["tds_status_read"];
        put: operations["tds_status_update"];
        post?: never;
        delete: operations["tds_status_delete"];
        options?: never;
        head?: never;
        patch: operations["tds_status_partial_update"];
        trace?: never;
    };
    "/tds/tds/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tds_tds_list"];
        put?: never;
        post: operations["tds_tds_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tds/tds/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Ficha Técnica. */
                id: number;
            };
            cookie?: never;
        };
        get: operations["tds_tds_read"];
        put: operations["tds_tds_update"];
        post?: never;
        delete: operations["tds_tds_delete"];
        options?: never;
        head?: never;
        patch: operations["tds_tds_partial_update"];
        trace?: never;
    };
    "/ticket/additional_request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ticket_additional_request_list"];
        put?: never;
        post: operations["ticket_additional_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ticket/additional_request/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Pedido Adicional. */
                id: number;
            };
            cookie?: never;
        };
        get: operations["ticket_additional_request_read"];
        put: operations["ticket_additional_request_update"];
        post?: never;
        delete: operations["ticket_additional_request_delete"];
        options?: never;
        head?: never;
        patch: operations["ticket_additional_request_partial_update"];
        trace?: never;
    };
    "/ticket/priority/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ticket_priority_list"];
        put?: never;
        post: operations["ticket_priority_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ticket/priority/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Prioridad. */
                id: number;
            };
            cookie?: never;
        };
        get: operations["ticket_priority_read"];
        put: operations["ticket_priority_update"];
        post?: never;
        delete: operations["ticket_priority_delete"];
        options?: never;
        head?: never;
        patch: operations["ticket_priority_partial_update"];
        trace?: never;
    };
    "/ticket/provider_company/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ticket_provider_company_list"];
        put?: never;
        post: operations["ticket_provider_company_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ticket/provider_company/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Empresa Proveedora. */
                id: number;
            };
            cookie?: never;
        };
        get: operations["ticket_provider_company_read"];
        put: operations["ticket_provider_company_update"];
        post?: never;
        delete: operations["ticket_provider_company_delete"];
        options?: never;
        head?: never;
        patch: operations["ticket_provider_company_partial_update"];
        trace?: never;
    };
    "/ticket/service_type/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ticket_service_type_list"];
        put?: never;
        post: operations["ticket_service_type_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ticket/service_type/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Tipo Servicio. */
                id: number;
            };
            cookie?: never;
        };
        get: operations["ticket_service_type_read"];
        put: operations["ticket_service_type_update"];
        post?: never;
        delete: operations["ticket_service_type_delete"];
        options?: never;
        head?: never;
        patch: operations["ticket_service_type_partial_update"];
        trace?: never;
    };
    "/ticket/task_category/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ticket_task_category_list"];
        put?: never;
        post: operations["ticket_task_category_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ticket/task_category/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Categoria Tarea. */
                id: number;
            };
            cookie?: never;
        };
        get: operations["ticket_task_category_read"];
        put: operations["ticket_task_category_update"];
        post?: never;
        delete: operations["ticket_task_category_delete"];
        options?: never;
        head?: never;
        patch: operations["ticket_task_category_partial_update"];
        trace?: never;
    };
    "/ticket/ticket_status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ticket_ticket_status_list"];
        put?: never;
        post: operations["ticket_ticket_status_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ticket/ticket_status/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Estado Ticket. */
                id: number;
            };
            cookie?: never;
        };
        get: operations["ticket_ticket_status_read"];
        put: operations["ticket_ticket_status_update"];
        post?: never;
        delete: operations["ticket_ticket_status_delete"];
        options?: never;
        head?: never;
        patch: operations["ticket_ticket_status_partial_update"];
        trace?: never;
    };
    "/ticket/ticket/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ticket_ticket_list"];
        put?: never;
        post: operations["ticket_ticket_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ticket/ticket/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Ticket Externo. */
                id: number;
            };
            cookie?: never;
        };
        get: operations["ticket_ticket_read"];
        put: operations["ticket_ticket_update"];
        post?: never;
        delete: operations["ticket_ticket_delete"];
        options?: never;
        head?: never;
        patch: operations["ticket_ticket_partial_update"];
        trace?: never;
    };
    "/ticket/tracking_history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ticket_tracking_history_list"];
        put?: never;
        post: operations["ticket_tracking_history_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ticket/tracking_history/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Historial Seguimiento. */
                id: number;
            };
            cookie?: never;
        };
        get: operations["ticket_tracking_history_read"];
        put: operations["ticket_tracking_history_update"];
        post?: never;
        delete: operations["ticket_tracking_history_delete"];
        options?: never;
        head?: never;
        patch: operations["ticket_tracking_history_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdditionalRequests: {
            /** Activo */
            active?: boolean;
            /**
             * Completion date
             * Format: date-time
             */
            completion_date?: string | null;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /** ID */
            readonly id?: number;
            /** Usuario solicitante interno */
            internal_requester?: number | null;
            /** Parent ticket */
            parent_ticket: number;
            /** Priority */
            priority?: number | null;
            /**
             * Request date
             * Format: date-time
             */
            request_date?: string | null;
            /** Request description */
            request_description: string;
            /** Request status */
            request_status?: number | null;
            /** Resolution description */
            resolution_description?: string | null;
            /** Sequence */
            sequence: number;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
        };
        Assets: {
            /** Area */
            area?: number | null;
            /** Edificio */
            building: number;
            /** Descripción */
            description?: string | null;
            /** ID */
            readonly id?: number;
            /** Inventario */
            inventory?: number | null;
            /** Dirección de red */
            networkaddress?: string | null;
            /** Situación */
            situation: number;
            /** Estado */
            state: number;
            /** Tipo Bien */
            typeasset: number;
            /** Ponderación */
            weighting: number;
        };
        AttachedDocument: {
            /** Activo */
            active?: number;
            /** Tipo de Documento adjunto */
            attached_type_document?: number | null;
            /** Empresa */
            company?: string | null;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /**
             * Date
             * Format: date
             */
            date?: string | null;
            /** Descripción */
            description?: string | null;
            /** ID */
            readonly id?: number;
            /** Nombre */
            name?: string | null;
            /** Numero */
            number?: string | null;
            /** Tipo */
            type?: string | null;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
        };
        Building: {
            /** Activo */
            active?: boolean;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /** Descripción */
            description?: string | null;
            /** ID */
            readonly id?: number;
            /** Nombre */
            name: string;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
        };
        Document: {
            /** Activo */
            active?: number;
            /** Area */
            area?: number | null;
            area_details?: components["schemas"]["DocumentArea"];
            readonly attached_documents?: components["schemas"]["AttachedDocument"][];
            attacheds?: (number | null)[];
            /** Bibliorato */
            bibliorato?: number | null;
            readonly children?: components["schemas"]["RecursiveField"][];
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /**
             * Fecha
             * Format: date
             */
            date?: string | null;
            /** Descripción */
            description?: string | null;
            /** ID */
            readonly id?: number;
            /** Ingreso/Egreso */
            input_output: string;
            /** Numero */
            number?: string | null;
            /** Parent info */
            readonly parent_info?: string;
            /** Referencia (Padre) */
            reference?: number | null;
            /** Alcance */
            scope_document?: string | null;
            /** Foja */
            total_page: number;
            /** Tipo de Documento */
            type_document: number;
            type_document_details?: components["schemas"]["TypeDocument"];
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
            /** Usuario */
            user: number;
            user_details?: components["schemas"]["User"];
            /** Año */
            year?: string | null;
        };
        DocumentArea: {
            /** ID */
            readonly id?: number;
            /** Nombre */
            name: string;
        };
        ExternalTickets: {
            /** Activo */
            active?: boolean;
            /** Category */
            category?: number | null;
            /** Company */
            company: number;
            /** Context */
            context?: string | null;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /** Description */
            description?: string | null;
            /** Direct ticket url */
            direct_ticket_url?: string | null;
            /**
             * External closing date
             * Format: date-time
             */
            external_closing_date?: string | null;
            /**
             * External opening date
             * Format: date-time
             */
            external_opening_date?: string | null;
            /** External ticket number */
            external_ticket_number?: string | null;
            /** General title */
            general_title: string;
            /** Global status */
            global_status?: number | null;
            /** ID */
            readonly id?: number;
            /** Priority */
            priority?: number | null;
            /** Usuario que registro */
            registration_agent?: number | null;
            /** Service type */
            service_type?: number | null;
            /** Simple action number */
            simple_action_number?: string | null;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
        };
        MyTokenObtainPair: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        Priorities: {
            /** Activo */
            active?: boolean;
            /** Code */
            code: string;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /** ID */
            readonly id?: number;
            /** Name */
            name: string;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
        };
        ProviderCompanies: {
            /** Activo */
            active?: boolean;
            /** Contact email */
            contact_email?: string | null;
            /** Contact name */
            contact_name?: string | null;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /** ID */
            readonly id?: number;
            /** Name */
            name: string;
            /** Support portal url */
            support_portal_url?: string | null;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
        };
        RecursiveField: Record<string, never>;
        ServiceTypes: {
            /** ID */
            readonly id?: number;
            /** Name */
            name: string;
        };
        Status: {
            /** Descripción */
            description?: string | null;
            /** ID */
            readonly id?: number;
            /** Nombre */
            name: string;
        };
        TaskCategories: {
            /** ID */
            readonly id?: number;
            /** Name */
            name: string;
        };
        TdsArea: {
            /** Activo */
            active?: boolean;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /** Descripción */
            description?: string | null;
            /** Email */
            email?: string | null;
            /** ID */
            readonly id?: number;
            /** Nombre */
            name: string;
            /** Teléfono */
            telephone?: string | null;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
        };
        TdsStatusUser: {
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /** ID */
            readonly id?: number;
            status?: components["schemas"]["Status"];
            /** Fichas Técnicas */
            tds: number;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
            users?: components["schemas"]["User"];
        };
        TechnicalDataSheetsRead: {
            /** Actuación Simple */
            act_simple?: string | null;
            /** Activo */
            active?: boolean;
            area?: components["schemas"]["TdsArea"];
            asset?: components["schemas"]["Assets"];
            /** Tipo de asistencia */
            assistance?: string | null;
            building?: components["schemas"]["Building"];
            /** Nombre del contacto */
            contact_name?: string | null;
            /** Teléfono de contacto */
            contact_phone?: string | null;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /**
             * Fecha de repación
             * Format: date
             */
            date?: string | null;
            /**
             * Fecha de ingreso
             * Format: date
             */
            date_in?: string | null;
            /**
             * Fecha de egreso
             * Format: date
             */
            date_out?: string | null;
            /** ID */
            readonly id?: number;
            /** Medio de solicitud */
            means_application?: string | null;
            /** Password usuario pc */
            pass_pc?: string | null;
            /** Retirado por */
            retired_by?: string | null;
            readonly status_users?: components["schemas"]["TdsStatusUser"][];
            /** Descripción del técnico */
            tech_description?: string | null;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
            /** Descripción del usuario */
            user_description?: string | null;
            /** Usuario pc */
            user_pc?: string | null;
            /** Año Actualización Simple */
            year_act_simple?: number | null;
        };
        TechnicalDataSheetsWrite: {
            /** Actuación Simple */
            act_simple?: string | null;
            /** Activo */
            active?: boolean;
            /** Area */
            area?: number | null;
            /** Asset */
            asset: number;
            /** Tipo de asistencia */
            assistance?: string | null;
            /** Building */
            building?: number | null;
            /** Nombre del contacto */
            contact_name?: string | null;
            /** Teléfono de contacto */
            contact_phone?: string | null;
            /**
             * Fecha de repación
             * Format: date
             */
            date?: string | null;
            /**
             * Fecha de ingreso
             * Format: date
             */
            date_in?: string | null;
            /**
             * Fecha de egreso
             * Format: date
             */
            date_out?: string | null;
            /** ID */
            readonly id?: number;
            /** Medio de solicitud */
            means_application?: string | null;
            /** Password usuario pc */
            pass_pc?: string | null;
            /** Retirado por */
            retired_by?: string | null;
            status?: number[];
            /** Descripción del técnico */
            tech_description?: string | null;
            /** Descripción del usuario */
            user_description?: string | null;
            /** Usuario pc */
            user_pc?: string | null;
            users?: number[];
            /** Año Actualización Simple */
            year_act_simple?: number | null;
        };
        TicketStatuses: {
            /** Activo */
            active?: boolean;
            /** Code */
            code: string;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /** Description */
            description?: string | null;
            /** ID */
            readonly id?: number;
            /** Name */
            name: string;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
        };
        TokenRefresh: {
            /** Access */
            readonly access?: string;
            /** Refresh */
            refresh: string;
        };
        TrackingHistory: {
            /** Activo */
            active?: boolean;
            /** Additional request */
            additional_request: number;
            /** Comment */
            comment?: string | null;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /**
             * Event date
             * Format: date-time
             */
            event_date?: string | null;
            /** ID */
            readonly id?: number;
            /** New status */
            new_status?: number | null;
            /** Previous status */
            previous_status?: number | null;
            /** Usuario que registro */
            registered_by_user?: number | null;
            /** Update source */
            update_source?: string | null;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
        };
        TypeDocument: {
            /** Activo */
            active?: number;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /** Descripción */
            description?: string | null;
            /** ID */
            readonly id?: number;
            /** Nombre */
            name: string;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
        };
        User: {
            /** Nombre */
            first_name?: string;
            /** ID */
            readonly id?: number;
            /** Apellido */
            last_name?: string;
            /**
             * Nombre de usuario
             * @description Obligatorio. Longitud máxima de 150 caracteres. Solo puede estar formado por letras, números y los caracteres @/./+/-/_.
             */
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        AdditionalRequests: {
            content: {
                "application/json": components["schemas"]["AdditionalRequests"];
            };
        };
        Assets: {
            content: {
                "application/json": components["schemas"]["Assets"];
            };
        };
        Document: {
            content: {
                "application/json": components["schemas"]["Document"];
            };
        };
        ExternalTickets: {
            content: {
                "application/json": components["schemas"]["ExternalTickets"];
            };
        };
        Priorities: {
            content: {
                "application/json": components["schemas"]["Priorities"];
            };
        };
        ProviderCompanies: {
            content: {
                "application/json": components["schemas"]["ProviderCompanies"];
            };
        };
        ServiceTypes: {
            content: {
                "application/json": components["schemas"]["ServiceTypes"];
            };
        };
        Status: {
            content: {
                "application/json": components["schemas"]["Status"];
            };
        };
        TaskCategories: {
            content: {
                "application/json": components["schemas"]["TaskCategories"];
            };
        };
        TechnicalDataSheetsWrite: {
            content: {
                "application/json": components["schemas"]["TechnicalDataSheetsWrite"];
            };
        };
        TicketStatuses: {
            content: {
                "application/json": components["schemas"]["TicketStatuses"];
            };
        };
        TrackingHistory: {
            content: {
                "application/json": components["schemas"]["TrackingHistory"];
            };
        };
        TypeDocument: {
            content: {
                "application/json": components["schemas"]["TypeDocument"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MyTokenObtainPair"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyTokenObtainPair"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    documents_document_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"][];
                };
            };
        };
    };
    documents_document_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Document"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    documents_document_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Documento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    documents_document_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Documento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Document"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    documents_document_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Documento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    documents_document_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Documento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Document"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    documents_typedocument_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeDocument"][];
                };
            };
        };
    };
    documents_typedocument_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TypeDocument"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeDocument"];
                };
            };
        };
    };
    documents_typedocument_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Tipo de Documento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeDocument"];
                };
            };
        };
    };
    documents_typedocument_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Tipo de Documento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TypeDocument"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeDocument"];
                };
            };
        };
    };
    documents_typedocument_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Tipo de Documento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    documents_typedocument_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Tipo de Documento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TypeDocument"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeDocument"];
                };
            };
        };
    };
    tds_assets_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assets"][];
                };
            };
        };
    };
    tds_assets_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Assets"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assets"];
                };
            };
        };
    };
    tds_assets_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Bien. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assets"];
                };
            };
        };
    };
    tds_assets_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Bien. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Assets"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assets"];
                };
            };
        };
    };
    tds_assets_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Bien. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tds_assets_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Bien. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Assets"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assets"];
                };
            };
        };
    };
    tds_status_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"][];
                };
            };
        };
    };
    tds_status_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Status"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    tds_status_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Estado. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    tds_status_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Estado. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Status"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    tds_status_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Estado. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tds_status_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Estado. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Status"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    tds_tds_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicalDataSheetsRead"][];
                };
            };
        };
    };
    tds_tds_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TechnicalDataSheetsWrite"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicalDataSheetsWrite"];
                };
            };
        };
    };
    tds_tds_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Ficha Técnica. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicalDataSheetsRead"];
                };
            };
        };
    };
    tds_tds_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Ficha Técnica. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TechnicalDataSheetsWrite"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicalDataSheetsWrite"];
                };
            };
        };
    };
    tds_tds_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Ficha Técnica. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tds_tds_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Ficha Técnica. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TechnicalDataSheetsRead"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicalDataSheetsRead"];
                };
            };
        };
    };
    ticket_additional_request_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdditionalRequests"][];
                };
            };
        };
    };
    ticket_additional_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["AdditionalRequests"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdditionalRequests"];
                };
            };
        };
    };
    ticket_additional_request_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Pedido Adicional. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdditionalRequests"];
                };
            };
        };
    };
    ticket_additional_request_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Pedido Adicional. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["AdditionalRequests"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdditionalRequests"];
                };
            };
        };
    };
    ticket_additional_request_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Pedido Adicional. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ticket_additional_request_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Pedido Adicional. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["AdditionalRequests"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdditionalRequests"];
                };
            };
        };
    };
    ticket_priority_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Priorities"][];
                };
            };
        };
    };
    ticket_priority_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Priorities"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Priorities"];
                };
            };
        };
    };
    ticket_priority_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Prioridad. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Priorities"];
                };
            };
        };
    };
    ticket_priority_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Prioridad. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Priorities"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Priorities"];
                };
            };
        };
    };
    ticket_priority_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Prioridad. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ticket_priority_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Prioridad. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Priorities"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Priorities"];
                };
            };
        };
    };
    ticket_provider_company_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderCompanies"][];
                };
            };
        };
    };
    ticket_provider_company_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ProviderCompanies"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderCompanies"];
                };
            };
        };
    };
    ticket_provider_company_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Empresa Proveedora. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderCompanies"];
                };
            };
        };
    };
    ticket_provider_company_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Empresa Proveedora. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ProviderCompanies"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderCompanies"];
                };
            };
        };
    };
    ticket_provider_company_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Empresa Proveedora. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ticket_provider_company_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Empresa Proveedora. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ProviderCompanies"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderCompanies"];
                };
            };
        };
    };
    ticket_service_type_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceTypes"][];
                };
            };
        };
    };
    ticket_service_type_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ServiceTypes"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceTypes"];
                };
            };
        };
    };
    ticket_service_type_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Tipo Servicio. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceTypes"];
                };
            };
        };
    };
    ticket_service_type_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Tipo Servicio. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ServiceTypes"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceTypes"];
                };
            };
        };
    };
    ticket_service_type_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Tipo Servicio. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ticket_service_type_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Tipo Servicio. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ServiceTypes"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceTypes"];
                };
            };
        };
    };
    ticket_task_category_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCategories"][];
                };
            };
        };
    };
    ticket_task_category_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TaskCategories"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCategories"];
                };
            };
        };
    };
    ticket_task_category_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Categoria Tarea. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCategories"];
                };
            };
        };
    };
    ticket_task_category_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Categoria Tarea. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TaskCategories"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCategories"];
                };
            };
        };
    };
    ticket_task_category_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Categoria Tarea. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ticket_task_category_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Categoria Tarea. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TaskCategories"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCategories"];
                };
            };
        };
    };
    ticket_ticket_status_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketStatuses"][];
                };
            };
        };
    };
    ticket_ticket_status_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TicketStatuses"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketStatuses"];
                };
            };
        };
    };
    ticket_ticket_status_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Estado Ticket. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketStatuses"];
                };
            };
        };
    };
    ticket_ticket_status_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Estado Ticket. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TicketStatuses"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketStatuses"];
                };
            };
        };
    };
    ticket_ticket_status_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Estado Ticket. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ticket_ticket_status_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Estado Ticket. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TicketStatuses"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketStatuses"];
                };
            };
        };
    };
    ticket_ticket_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalTickets"][];
                };
            };
        };
    };
    ticket_ticket_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ExternalTickets"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalTickets"];
                };
            };
        };
    };
    ticket_ticket_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Ticket Externo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalTickets"];
                };
            };
        };
    };
    ticket_ticket_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Ticket Externo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ExternalTickets"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalTickets"];
                };
            };
        };
    };
    ticket_ticket_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Ticket Externo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ticket_ticket_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Ticket Externo. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ExternalTickets"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalTickets"];
                };
            };
        };
    };
    ticket_tracking_history_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingHistory"][];
                };
            };
        };
    };
    ticket_tracking_history_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TrackingHistory"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingHistory"];
                };
            };
        };
    };
    ticket_tracking_history_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Historial Seguimiento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingHistory"];
                };
            };
        };
    };
    ticket_tracking_history_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Historial Seguimiento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TrackingHistory"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingHistory"];
                };
            };
        };
    };
    ticket_tracking_history_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Historial Seguimiento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ticket_tracking_history_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Historial Seguimiento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TrackingHistory"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackingHistory"];
                };
            };
        };
    };
}
