/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/document/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["documents_document_list"];
        put?: never;
        post: operations["documents_document_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/document/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Documento. */
                id: number;
            };
            cookie?: never;
        };
        get: operations["documents_document_read"];
        put: operations["documents_document_update"];
        post?: never;
        delete: operations["documents_document_delete"];
        options?: never;
        head?: never;
        patch: operations["documents_document_partial_update"];
        trace?: never;
    };
    "/documents/typedocument/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["documents_typedocument_list"];
        put?: never;
        post: operations["documents_typedocument_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/typedocument/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Tipo de Documento. */
                id: number;
            };
            cookie?: never;
        };
        get: operations["documents_typedocument_read"];
        put: operations["documents_typedocument_update"];
        post?: never;
        delete: operations["documents_typedocument_delete"];
        options?: never;
        head?: never;
        patch: operations["documents_typedocument_partial_update"];
        trace?: never;
    };
    "/tds/assets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tds_assets_list"];
        put?: never;
        post: operations["tds_assets_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tds/assets/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Bien. */
                id: number;
            };
            cookie?: never;
        };
        get: operations["tds_assets_read"];
        put: operations["tds_assets_update"];
        post?: never;
        delete: operations["tds_assets_delete"];
        options?: never;
        head?: never;
        patch: operations["tds_assets_partial_update"];
        trace?: never;
    };
    "/tds/status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tds_status_list"];
        put?: never;
        post: operations["tds_status_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tds/status/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Estado. */
                id: number;
            };
            cookie?: never;
        };
        get: operations["tds_status_read"];
        put: operations["tds_status_update"];
        post?: never;
        delete: operations["tds_status_delete"];
        options?: never;
        head?: never;
        patch: operations["tds_status_partial_update"];
        trace?: never;
    };
    "/tds/tds/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tds_tds_list"];
        put?: never;
        post: operations["tds_tds_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tds/tds/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Ficha Técnica. */
                id: number;
            };
            cookie?: never;
        };
        get: operations["tds_tds_read"];
        put: operations["tds_tds_update"];
        post?: never;
        delete: operations["tds_tds_delete"];
        options?: never;
        head?: never;
        patch: operations["tds_tds_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MyTokenObtainPair: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        TokenRefresh: {
            /** Refresh */
            refresh: string;
            /** Access */
            readonly access?: string;
        };
        TypeDocument: {
            /** ID */
            readonly id?: number;
            /** Nombre */
            name: string;
            /** Descripción */
            description?: string | null;
            /** Activo */
            active?: number;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
        };
        User: {
            /** ID */
            readonly id?: number;
            /**
             * Nombre de usuario
             * @description Obligatorio. Longitud máxima de 150 caracteres. Solo puede estar formado por letras, números y los caracteres @/./+/-/_.
             */
            username: string;
            /** Nombre */
            first_name?: string;
            /** Apellido */
            last_name?: string;
        };
        DocumentArea: {
            /** ID */
            readonly id?: number;
            /** Nombre */
            name: string;
        };
        AttachedDocument: {
            /** ID */
            readonly id?: number;
            /** Nombre */
            name?: string | null;
            /** Tipo */
            type?: string | null;
            /** Descripción */
            description?: string | null;
            /**
             * Date
             * Format: date
             */
            date?: string | null;
            /** Empresa */
            company?: string | null;
            /** Numero */
            number?: string | null;
            /** Activo */
            active?: number;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
            /** Tipo de Documento adjunto */
            attached_type_document?: number | null;
        };
        RecursiveField: Record<string, never>;
        Document: {
            /** ID */
            readonly id?: number;
            /** Numero */
            number?: string | null;
            /** Año */
            year?: string | null;
            /**
             * Fecha
             * Format: date
             */
            date?: string | null;
            /** Ingreso/Egreso */
            input_output: string;
            /** Foja */
            total_page: number;
            /** Alcance */
            scope_document?: string | null;
            /** Descripción */
            description?: string | null;
            /** Activo */
            active?: number;
            /** Tipo de Documento */
            type_document: number;
            /** Usuario */
            user: number;
            /** Area */
            area?: number | null;
            /** Bibliorato */
            bibliorato?: number | null;
            /** Referencia (Padre) */
            reference?: number | null;
            attacheds?: (number | null)[];
            type_document_details?: components["schemas"]["TypeDocument"];
            user_details?: components["schemas"]["User"];
            area_details?: components["schemas"]["DocumentArea"];
            /** Parent info */
            readonly parent_info?: string;
            readonly attached_documents?: components["schemas"]["AttachedDocument"][];
            readonly children?: components["schemas"]["RecursiveField"][];
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
        };
        Assets: {
            /** ID */
            readonly id?: number;
            /** Inventario */
            inventory?: number | null;
            /** Descripción */
            description?: string | null;
            /** Tipo Bien */
            typeasset: number;
            /** Area */
            area?: number | null;
            /** Edificio */
            building: number;
            /** Situación */
            situation: number;
            /** Ponderación */
            weighting: number;
            /** Estado */
            state: number;
        };
        Status: {
            /** ID */
            readonly id?: number;
            /** Nombre */
            name: string;
            /** Descripción */
            description?: string | null;
        };
        TdsArea: {
            /** ID */
            readonly id?: number;
            /** Nombre */
            name: string;
            /** Descripción */
            description?: string | null;
            /** Email */
            email?: string | null;
            /** Teléfono */
            telephone?: string | null;
            /** Activo */
            active?: boolean;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
        };
        Building: {
            /** ID */
            readonly id?: number;
            /** Nombre */
            name: string;
            /** Descripción */
            description?: string | null;
            /** Activo */
            active?: boolean;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
        };
        TdsStatusUser: {
            /** ID */
            readonly id?: number;
            /** Fichas Técnicas */
            tds: number;
            status?: components["schemas"]["Status"];
            users?: components["schemas"]["User"];
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
        };
        TechnicalDataSheetsRead: {
            /** ID */
            readonly id?: number;
            /** Actuación Simple */
            act_simple?: string | null;
            /** Año Actualización Simple */
            year_act_simple?: number | null;
            /** Descripción del usuario */
            user_description?: string | null;
            /** Descripción del técnico */
            tech_description?: string | null;
            /**
             * Fecha de repación
             * Format: date
             */
            date?: string | null;
            /** Usuario pc */
            user_pc?: string | null;
            /** Password usuario pc */
            pass_pc?: string | null;
            /** Nombre del contacto */
            contact_name?: string | null;
            /** Teléfono de contacto */
            contact_phone?: string | null;
            /** Medio de solicitud */
            means_application?: string | null;
            /** Tipo de asistencia */
            assistance?: string | null;
            /**
             * Fecha de ingreso
             * Format: date
             */
            date_in?: string | null;
            /**
             * Fecha de egreso
             * Format: date
             */
            date_out?: string | null;
            /** Retirado por */
            retired_by?: string | null;
            /** Activo */
            active?: boolean;
            /**
             * Fecha de creación
             * Format: date-time
             */
            readonly createdat?: string;
            /**
             * Fecha de actualización
             * Format: date-time
             */
            readonly updatedat?: string;
            asset?: components["schemas"]["Assets"];
            area?: components["schemas"]["TdsArea"];
            building?: components["schemas"]["Building"];
            readonly status_users?: components["schemas"]["TdsStatusUser"][];
        };
        TechnicalDataSheetsWrite: {
            /** ID */
            readonly id?: number;
            /** Actuación Simple */
            act_simple?: string | null;
            /** Año Actualización Simple */
            year_act_simple?: number | null;
            /** Descripción del usuario */
            user_description?: string | null;
            /** Descripción del técnico */
            tech_description?: string | null;
            /**
             * Fecha de repación
             * Format: date
             */
            date?: string | null;
            /** Usuario pc */
            user_pc?: string | null;
            /** Password usuario pc */
            pass_pc?: string | null;
            /** Nombre del contacto */
            contact_name?: string | null;
            /** Teléfono de contacto */
            contact_phone?: string | null;
            /** Medio de solicitud */
            means_application?: string | null;
            /** Tipo de asistencia */
            assistance?: string | null;
            /**
             * Fecha de ingreso
             * Format: date
             */
            date_in?: string | null;
            /**
             * Fecha de egreso
             * Format: date
             */
            date_out?: string | null;
            /** Retirado por */
            retired_by?: string | null;
            /** Activo */
            active?: boolean;
            /** Asset */
            asset: number;
            /** Area */
            area?: number | null;
            /** Building */
            building?: number | null;
            status?: number[];
            users?: number[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: {
        Status: {
            content: {
                "application/json": components["schemas"]["Status"];
            };
        };
        Assets: {
            content: {
                "application/json": components["schemas"]["Assets"];
            };
        };
        TechnicalDataSheetsWrite: {
            content: {
                "application/json": components["schemas"]["TechnicalDataSheetsWrite"];
            };
        };
        Document: {
            content: {
                "application/json": components["schemas"]["Document"];
            };
        };
        TypeDocument: {
            content: {
                "application/json": components["schemas"]["TypeDocument"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MyTokenObtainPair"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyTokenObtainPair"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    documents_document_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"][];
                };
            };
        };
    };
    documents_document_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Document"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    documents_document_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Documento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    documents_document_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Documento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Document"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    documents_document_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Documento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    documents_document_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Documento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Document"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    documents_typedocument_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeDocument"][];
                };
            };
        };
    };
    documents_typedocument_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TypeDocument"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeDocument"];
                };
            };
        };
    };
    documents_typedocument_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Tipo de Documento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeDocument"];
                };
            };
        };
    };
    documents_typedocument_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Tipo de Documento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TypeDocument"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeDocument"];
                };
            };
        };
    };
    documents_typedocument_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Tipo de Documento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    documents_typedocument_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Tipo de Documento. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TypeDocument"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeDocument"];
                };
            };
        };
    };
    tds_assets_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assets"][];
                };
            };
        };
    };
    tds_assets_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Assets"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assets"];
                };
            };
        };
    };
    tds_assets_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Bien. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assets"];
                };
            };
        };
    };
    tds_assets_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Bien. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Assets"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assets"];
                };
            };
        };
    };
    tds_assets_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Bien. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tds_assets_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Bien. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Assets"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assets"];
                };
            };
        };
    };
    tds_status_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"][];
                };
            };
        };
    };
    tds_status_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Status"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    tds_status_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Estado. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    tds_status_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Estado. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Status"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    tds_status_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Estado. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tds_status_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Estado. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Status"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    tds_tds_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicalDataSheetsRead"][];
                };
            };
        };
    };
    tds_tds_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TechnicalDataSheetsWrite"];
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicalDataSheetsWrite"];
                };
            };
        };
    };
    tds_tds_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Ficha Técnica. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicalDataSheetsRead"];
                };
            };
        };
    };
    tds_tds_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Ficha Técnica. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["TechnicalDataSheetsWrite"];
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicalDataSheetsWrite"];
                };
            };
        };
    };
    tds_tds_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Ficha Técnica. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tds_tds_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Ficha Técnica. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TechnicalDataSheetsRead"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicalDataSheetsRead"];
                };
            };
        };
    };
}
